name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Bug Report
        
        Thank you for taking the time to report a bug! Please provide as much detail as possible to help us reproduce and fix the issue.
        
        ---

  - type: dropdown
    id: product
    attributes:
      label: 📦 Product
      description: Which Proxy Mocksy product are you using?
      options:
        - CLI (@proxy-mocksy/cli)
        - VS Code Extension
        - Docker Image
        - Core Library (@proxy-mocksy/core)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: 🚀 Deployment/Installation Method
      description: How did you install or deploy Proxy Mocksy?
      options:
        - NPM (npm install)
        - JSR (jsr add)
        - VS Code Marketplace
        - Docker Hub
        - Built from source
      default: 0
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📋 Version
      description: What version are you using? (Check package.json, extension details, or `--version` flag)
      placeholder: "e.g., 0.0.15, latest, main"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 💻 Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL/Fedora)
        - Linux (Arch)
        - Linux (Other)
        - Docker Container
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: 🟢 Node.js Version (if applicable)
      description: What version of Node.js are you using? (Run `node --version`)
      placeholder: "e.g., v18.17.0, v20.11.0"

  - type: input
    id: deno-version
    attributes:
      label: 🦕 Deno Version (if applicable)
      description: What version of Deno are you using? (Run `deno --version`)
      placeholder: "e.g., deno 1.46.3, deno 2.0.0"

  - type: input
    id: vscode-version
    attributes:
      label: 🔵 VS Code Version (if applicable)
      description: What version of VS Code are you using? (Help > About)
      placeholder: "e.g., 1.102.0"

  - type: textarea
    id: description
    attributes:
      label: 📝 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What did you expect to happen?
      placeholder: "Describe what you expected..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened instead?
      placeholder: "Describe what actually happened..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Start the server with...
        2. Configure the endpoint...
        3. Make a request to...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: ⚙️ Configuration
      description: Share your proxy-mocksy.config.json (remove sensitive data)
      render: json
      placeholder: |
        {
          "server": {
            "port": 3001
          },
          "endpoints": [
            // Your configuration here
          ]
        }

  - type: textarea
    id: logs
    attributes:
      label: 📄 Logs/Error Messages
      description: Include any relevant console output, error messages, or stack traces
      render: shell
      placeholder: "Paste logs here..."

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context
      description: |
        Add any other context about the problem here:
        - Screenshots
        - Related issues
        - Workarounds you've tried
        - Environment details
      placeholder: "Any additional information..."

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I have removed any sensitive information from my configuration
          required: true
