name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # ✨ Feature Request
        
        Thank you for suggesting a new feature! Your ideas help make Proxy Mocksy better for everyone.
        
        ---

  - type: dropdown
    id: product
    attributes:
      label: 📦 Product
      description: Which Proxy Mocksy product should this feature be added to?
      multiple: true
      options:
        - CLI (@proxy-mocksy/cli)
        - VS Code Extension
        - Docker Image
        - Core Library (@proxy-mocksy/core)
        - Documentation
        - All Products
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my use case
      default: 1
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 📋 Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve? What's your current pain point?
      placeholder: |
        Currently, when I try to...
        The problem is...
        This makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        I would like to be able to...
        This could work by...
        The feature should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
        Current workaround: ...

  - type: textarea
    id: use-cases
    attributes:
      label: 🎯 Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Use Case 1: When developing a React app, I want to...
        Use Case 2: For API testing, it would be helpful to...
        Use Case 3: In a team environment, we need to...

  - type: textarea
    id: mockup
    attributes:
      label: 🎨 Mockup/Design Ideas
      description: |
        If applicable, provide mockups, sketches, or describe the UI/UX you envision.
        You can drag and drop images here.
      placeholder: |
        Configuration example:
        ```json
        {
          "newFeature": {
            "enabled": true,
            "options": {...}
          }
        }
        ```
        
        CLI usage:
        ```bash
        proxy-mocksy --new-feature
        ```

  - type: dropdown
    id: complexity
    attributes:
      label: 🔧 Implementation Complexity (Your Estimate)
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change/addition
        - Medium - Moderate effort required
        - Complex - Significant development work
        - Major - Large architectural changes
        - Unknown - I'm not sure
      default: 4

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context
      description: |
        Add any other context, screenshots, links, or examples about the feature request here:
        - Links to similar features in other tools
        - Screenshots or mockups
        - Related documentation
        - Community discussions
      placeholder: "Any additional information..."

  - type: checkboxes
    id: implementation
    attributes:
      label: 🛠️ Implementation
      description: Are you interested in contributing to this feature?
      options:
        - label: I would be willing to implement this feature myself
        - label: I would be willing to test this feature when implemented
        - label: I would be willing to provide feedback during development
        - label: I would be willing to help with documentation

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: This feature request is specific and actionable
          required: true
        - label: I have provided clear use cases and examples
          required: true
